test: &default

  # Credentials for REST APIs
  client_id: ARzf8qxhZFUWzDab5wdn2cOkZXC-HIyEYs2HHgUKj5PtjoLWMbHfTiiPaYBFIEc0a5bmgrs5yvcGITOU
  client_secret: EAIJgmSofQx1aI5J83aK_214UQlVPJbZ_Y96zy2cfPEPPWJPYMDc-QnW6mQd40Ea0el5B6fECd6dnc9E
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: mario.miranda.luengo@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
